server:
  port : 20000

spring:
  application:
    name: "@project.name@"
  cloud:
    gateway:
      routes:
        - id: peopleModuleV1
          uri: http://localhost:30000
          predicates:
            - Path=/people-module/**
          filters:
            - RewritePath=/people-module, /
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:40005/auth/realms/demorealm